### ISSUE TITLE
Xml Validation Error 306 is throwing erroneously on drugs with two different measurement types.

### ISSUE THREAD

**Issue by aorin123** [SEARCH-NCJIS/nibrs#13]
This exception is being ignored by getRule306ForPropertyDescriptions:

Rule 306 Exception:
1) When a data value is entered in both Drug Type 1 and Drug Type 2, but different measurement categories are entered in Data Element 22 (Type Drug Measurement); this is allowed. Refer to Data Element

Attached example showing the issue.
[306Error.txt](https://github.com/SEARCH-NCJIS/nibrs/files/2112618/306Error.txt)

**Comment by haiqi** [comment]
Hi, 

Thanks for reporting the issue.  After some investigation, the exception is actually for dataElement 20's rule 306 validation which is implemented in getRule306.  "getRule306ForPropertyDescriptions" is for DE 15, the property description.  

So the problem is there are two property description 10 in the parsed PropertySegment. This is caused by a XMLIncidentBuilder's  bug in parsing the "Substance" elements.  Because the flat file layout has it that a property segment can have multiple suspected drugs for one property description 10. So when parsing multiple "Substance" elements, we should have only one property description 10 in the propertySegment with the same property loss type.  We should also add the values up to the value of property of the property description 10.  

The issue is fixed in these commits df1e30b71ab7a497200104d96f58a7a897214d21 and dc88c69e4c71338fe90f55af88b1be4aa08af972.

**Comment by aorin123** [comment]
Got it thanks.
